feat: t10 - chapter3-t10 nginx.conf file
darliiin/devops-camp-2023 pull request #10
Opened 2023-04-15 08:05 UTC by darliiin

**Summary**
**Test Task**
**implement your test host**

- setup nginx supporting 2 servers
- camp-php.local (this will be used for future php experiments)
- camp-python.local (this will be used for future python experiments)
- both servers should support named certificates for the domains mentioned above. use mkcert cli to do that
- both server should implement custom location /hello, that will return 200 OK status code along with the value of the query_string passed into that URL, [see here](https://www.techopedia.com/definition/1228/query-string), for example https://camp-php.local/hello?tech_stack=php, which should output the entire query_string
- your SSL cert should be valid in CURL call in CLI, as well as if you open it in the browser
- your camp-php.local server should output logs in JSON format
- open PR when you done, in the PR - pls demonstrate the output of the curl call for the URL in each domain, and the screenshot in the browser

`curl -I https://camp-php.local`
```
HTTP/2 200 
server: nginx/1.22.0 (Ubuntu)
date: Sat, 15 Apr 2023 08:04:03 GMT
content-type: text/html
content-length: 246
last-modified: Mon, 10 Apr 2023 14:03:03 GMT
etag: "64341717-f6"
accept-ranges: bytes
```
**my results**
` curl -I https://camp-pyton.local`
```
HTTP/2 200 
server: nginx/1.22.0 (Ubuntu)
date: Sat, 15 Apr 2023 08:04:10 GMT
content-type: text/html
content-length: 250
last-modified: Mon, 10 Apr 2023 15:39:15 GMT
etag: "64342da3-fa"
accept-ranges: bytes
```
![Screenshot_20230415_120812](https://user-images.githubusercontent.com/117597862/232199138-59ea3561-61f6-46d7-a160-7a86956f49e5.png)

2023-04-18 23:45 UTC, dmitry-mightydevops requested changes

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +        include /etc/nginx/sites-enabled/*;
you solution should be self sufficient, without the includes

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +               '"http_user_agent": "$http_user_agent" }';
see how to format this block better.

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +                listen [::]:80;
no need for http, if we have superior https

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +                access_log /var/log/nginx/camp-php.local_access.log json;
don't put anything after locations. All your server related directives should be above the locations. and grouped by "purpose", i.e. access_log and error_log should come together one after another.

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +                        return 200 $args;
prefer tabs to spaces

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +        }
same nuances applied here.

2023-04-18 23:45 UTC, dmitry-mightydevops commented on chapter3/tests/t10/nginx.conf
> +                        return 200 $args;
that is correct implementation - good job!

2023-04-20 00:05 UTC, dmitry-mightydevops requested changes
pls follow the workflow
if you addressed the change - pls mark feedback comment with reply "Done" at minimum

2023-04-20 05:20 UTC, darliiin commented on chapter3/tests/t10/nginx.conf
> +        }
done

2023-04-20 05:20 UTC, darliiin commented on chapter3/tests/t10/nginx.conf
> +                        return 200 $args;
done

2023-04-20 05:20 UTC, darliiin commented on chapter3/tests/t10/nginx.conf
> +                access_log /var/log/nginx/camp-php.local_access.log json;
done

2023-04-20 05:20 UTC, darliiin commented on chapter3/tests/t10/nginx.conf
> +                listen [::]:80;
done

2023-04-20 05:21 UTC, darliiin commented on chapter3/tests/t10/nginx.conf
> +               '"http_user_agent": "$http_user_agent" }';
done

2023-04-20 17:08 UTC, dmitry-mightydevops approved these changes

2023-04-26 06:24 UTC, merged