feat: t13 - chapter4-t13-fetris
darliiin/devops-camp-2023 pull request #12
Opened 2023-04-18 19:38 UTC by darliiin

# Summary
## Test task

- форкните этот репозиторий https://github.com/udaltsovra/flatris
- напишите Dockerfile для сборки приложения для следующих архитектур
linux/amd64
linux/arm/v8
linux/arm64
- напишите docker-compose файл, который будет запускать приложение
работоспособность приложения можно проверить в браузере
работоспособность приложения можно проверить в консоли
`curl -I http://localhost/`

**Задание считается выполненным**
- Предоставлена ссылка на репозиторий с файлами
Dockerfile
docker-compose.yaml
- Предоставлен скриншот рабочего приложения
- Предоставлен скриншот с hub.docker.com с тегами для разных архитектур

## My results
Ссылка на репозиторий с файлами:
https://github.com/darliiin/flatris

![1](https://user-images.githubusercontent.com/117597862/232886529-6ace8984-5067-457d-b60c-77a4717ed1ee.png)
![2](https://user-images.githubusercontent.com/117597862/232886547-4a9d10d8-c69f-4894-9adc-45969ca97467.png)

2023-04-18 23:21 UTC, dmitry-mightydevops requested changes
no files except the images - impossible to review :)

2023-04-19 14:54 UTC, dmitry-mightydevops commented
@darliiin 
not following the workflow
a. Rostislav was not invited
b. You didn't re-request the review from me. `Needs Review` means you need to re-request all reviewers who rejected the review again
![image](https://user-images.githubusercontent.com/70822710/233115150-c9c7774d-0710-4372-a65b-0921ec230f95.png)

2023-04-20 00:08 UTC, dmitry-mightydevops requested changes

2023-04-20 00:08 UTC, dmitry-mightydevops commented on chapter4/tests/t13/Dockerfile
> +RUN NODE_OPTIONS=--openssl-legacy-provider yarn build
combine into one RUN

2023-04-20 00:08 UTC, dmitry-mightydevops commented on chapter4/tests/t13/Dockerfile
> +FROM --platform=$BUILDPLATFORM node:19.9.0
Declare ARG

2023-04-20 00:08 UTC, dmitry-mightydevops commented on chapter4/tests/t13/Dockerfile
> +CMD ["yarn", "start"]
Prefer ENTRYPOINT to CMD

2023-04-20 02:18 UTC, udaltsovra commented on chapter4/tests/t13/docker-compose.yaml
> +      - "3001:3001"
Have you changed the port that the application listens to inside the container?

2023-04-21 12:44 UTC, darliiin commented on chapter4/tests/t13/docker-compose.yaml
> +      - "3001:3001"
I forgot to change it to correct, fixed

2023-04-21 12:44 UTC, darliiin commented on chapter4/tests/t13/Dockerfile
> +CMD ["yarn", "start"]
done

2023-04-21 12:44 UTC, darliiin commented on chapter4/tests/t13/Dockerfile
> +FROM --platform=$BUILDPLATFORM node:19.9.0
done

2023-04-21 12:44 UTC, darliiin commented on chapter4/tests/t13/Dockerfile
> +RUN NODE_OPTIONS=--openssl-legacy-provider yarn build
almost done..

2023-04-24 06:19 UTC, udaltsovra commented on chapter4/tests/t13/Dockerfile
> +COPY . /app
Instruction [COPY](https://docs.docker.com/engine/reference/builder/#copy) copies data from the host file system to the host system of the image. In this case, you copy the contents of the build context to the image, and the previously created repository folder is located one level higher. The file sequence follows.

![image](https://user-images.githubusercontent.com/114897334/233914578-bae85598-10e9-404b-b592-9f2b04b4cc93.png)

Something like the following happens in your container. Use the dive utility to view the state of layers after creating an image.

2023-04-24 20:02 UTC, dmitry-mightydevops commented
@darliiin if you added WIP - why PR is in the OPEN state? It should be DRAFT.

2023-04-25 01:23 UTC, udaltsovra commented on chapter4/tests/t13/Dockerfile
> +COPY ../ /app
What are you trying to copy in this manual? This would be relevant if the repository folder was on the host, one level above the build context. 
Proceed sequentially: 
1. clone
2. go to the data folder
3. build.

2023-04-25 01:23 UTC, udaltsovra commented on chapter4/tests/t13/Dockerfile
> +    yarn install && \
You have cloned the repository in app/flatrec, but you are trying to build from the current directory.
You specify `WORKDIR /app`, and then clone `git clone https://github.com/udaltsovra/flatris app/flatris`. This will cause another directory named app to appear in the working directory.

2023-04-25 06:56 UTC, darliiin commented on chapter4/tests/t13/Dockerfile
> +COPY ../ /app
done

2023-04-25 06:57 UTC, darliiin commented on chapter4/tests/t13/Dockerfile
> +    yarn install && \
ok, got it

2023-04-25 19:40 UTC, dmitry-mightydevops approved these changes

2023-04-26 01:50 UTC, udaltsovra approved these changes

2023-04-26 05:29 UTC, merged