feat: t11 - chapter3-t11-php
darliiin/devops-camp-2023 pull request #13
Opened 2023-04-21 19:13 UTC by darliiin

# Summary
## Test Task
**slow php reporting page**
A typical scenario:
- you have a web app
- that app has a backend written in PHP
- most of the backend works fast and good for end users < 1000ms
- however there is a slow page /reports/slow, that takes 10m to execute, which causes nginx and php to timeout
- implement such solution so that nginx/php-fpm do not timeout and get the report when 10m passed.

Implementation nuances:
- your nginx and php-fpm should run under nginx/nginx user/group.
- use sleep php func to simulate such report, https://www.php.net/manual/en/function.sleep.php
- implement a custom location /reports/fast, that will work fast and doesn't require any timeouts, and will use www pool of the PHP-FPM
- implement a custom location /reports/slow, that will open /tmp/nginx/reports/slow.php script, which will take 10m to execute
- during the /reports/slow, you should not lose the browser connection to the server.
- IMPORTANT: you can't change any values for your core application that runs inside www pool defined in the PHP-FPM, for example you can't change timeout via www pool, as that may substantially degrade all the other URLs that are working good and fast - so think how you can do it.

When you open PR - pls package your solution as zip file with bash script run.sh that should
- create all necessary files and/or folders.
- set proper permissions to created files/folders
- start nginx in foreground mode (so all errors, logs are printed on stdout/stderr)
- start php-fpm in foreground mode (so all errors, logs are printed on stdout/stderr)
- curl https://localhost/reports/fast should output "FAST REPORT" via PHP script
- curl https://localhost/reports/slow should output "SLOW REPORT" via PHP script with 10m delay without losing any connection (i.e. no timeout or upstream timeout error in the nginx)

# My results
```
curl https://localhost/reports/fast
curl https://localhost/reports/slow
```
**output:**
```
FAST REPORT
SLOW REPORT
```
[t11.zip](https://github.com/darliiin/devops-camp-2023/files/11298642/t11.zip)

2023-04-24 20:17 UTC, dmitry-mightydevops requested changes
prove that your connection stayed 10m with `time curl URL`

2023-04-24 20:17 UTC, dmitry-mightydevops commented on chapter3/tests/t11/nginx.conf
> +	upstream reports {
that is not enough you need to have a dedicated php-fpm pool in which you set timeout for php scripts via `php_admin` call.

and your slow page should use that php-fpm 'slow' pool

2023-04-24 20:17 UTC, dmitry-mightydevops commented on chapter3/tests/t11/nginx.conf
> +			fastcgi_read_timeout 600s;
that is not enough you need to have a dedicated php-fpm pool in which you set timeout for php scripts via `php_admin` call.

for example your worker will wait for 10m - great, but your php.ini has value that scripts should timeout after 30s. 

That's why you need a dedicated pool used by a specific location `/reports/slow`

2023-04-24 20:17 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php-fpm.conf
> +[www]
need dedicated `[slow]` pool

2023-04-24 20:17 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php-fpm.conf
> +group = nginx
this should be in the global

2023-04-26 19:09 UTC, darliiin commented on chapter3/tests/t11/php-fpm.conf
> +group = nginx
done

2023-04-26 19:09 UTC, darliiin commented on chapter3/tests/t11/nginx.conf
> +			fastcgi_read_timeout 600s;
done

2023-04-26 19:09 UTC, darliiin commented on chapter3/tests/t11/nginx.conf
> +	upstream reports {
done

2023-04-26 20:02 UTC, dmitry-mightydevops requested changes

2023-04-26 20:02 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php-fpm.conf
> +php_admin_value[execution_time_limit] = 600
how  did you test? it shouuld complain on this value - there is no such setting in php.ini

2023-04-26 20:02 UTC, dmitry-mightydevops commented on chapter3/tests/t11/run.sh
> +curl https://localhost/reports/slow
use `time`, i.e. `time curl URL`

2023-04-28 07:23 UTC, darliiin commented on chapter3/tests/t11/run.sh
> +curl https://localhost/reports/slow
done

2023-04-28 07:24 UTC, darliiin commented on chapter3/tests/t11/php-fpm.conf
> +php_admin_value[execution_time_limit] = 600
updated php ini

2023-04-28 20:21 UTC, dmitry-mightydevops requested changes

2023-04-28 20:21 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php-fpm.conf
> +php_admin_value[execution_time_limit] = 600
you should not update php.ini - you should use proper value for php_admin_value in the php-fpm.conf

2023-04-28 20:21 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php.ini
> +php_admin_value max_execution_timeout = 30s
incorrect.

2023-04-28 20:21 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php.ini
> +php_admin_value max_execution_timeout = 30s
you have slow and fast php-fpm pools
fast - should limit execution time to 60s
slow - to 600s

that should not be defined in php.ini

2023-04-29 06:27 UTC, darliiin commented on chapter3/tests/t11/php.ini
> +php_admin_value max_execution_timeout = 30s
corrected

2023-04-30 02:26 UTC, dmitry-mightydevops requested changes

2023-04-30 02:26 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php-fpm.conf
> +php_admin_value[max_execution_time] = 600
you should have one in the [www] pool to limit to 60s

2023-04-30 02:26 UTC, dmitry-mightydevops commented on chapter3/tests/t11/php-fpm.conf
> +php_admin_value[max_execution_time] = 600
please perform the change and show me `time ` output for both URls

2023-04-30 08:36 UTC, darliiin commented on chapter3/tests/t11/php-fpm.conf
> +php_admin_value[max_execution_time] = 600
![Screenshot_20230430_132844](https://user-images.githubusercontent.com/117597862/235343776-4946608e-3e0b-47de-a51b-ac149516bd70.png)

2023-04-30 19:57 UTC, dmitry-mightydevops approved these changes

2023-05-01 08:34 UTC, merged