feat: t11 - chapter4-t14-compile distroless python3 OOM container
darliiin/devops-camp-2023 pull request #14
Opened 2023-04-25 19:14 UTC by darliiin

# Summary
## Test task
**compile distroless python3 OOM container**

Compile container using distroless base python3 image
<https://github.com/GoogleContainerTools/distroless>

See python files in **testtask** folder.

What you will need to do:

- setup pre-commit in the folder to run <https://github.com/hadolint/hadolint> checks against any Dockerfiles
  - don't open any PR if your Dockerfile does not pass validation from the linter.
- provide README.md with instructions how to run/test your work
- create Makefile with the following targets:
  - `build`
  - `run`
    - `run` target should accept parameter `limit` that will set the desired max memory limit for the running docker container
    - if such parameter is not set, a default value of **100m** should be used
- `make run` should start the docker container and output content similar to 
  ```sh
  Usage over time: [20.67578125, 20.67578125, 35.30078125, 50.17578125, 64.80078125, 79.55078125, 94.30078125, 20.734375]
  Peak usage: 94.30078125
  ```
- `make run` with optional argument for memory set at **30m** should understand that container exited by error and in this case output the following line
  ```sh
  {exited false false false true false 0 137  2023-04-17T00:50:11.053754525Z 2023-04-17T00:50:13.721847306Z <nil>}
  ```
  which is content of the docker **State** value.
  
 ## my results
`make run `

**output**:
```                
Usage over time: [21.9375, 22.0390625, 24.859375, 27.453125, 30.2890625, 33.03125, 36.3828125, 39.4765625, 42.4609375, 45.8125, 49.1640625, 53.03125, 56.640625, 60.42578125, 63.06640625, 66.93359375, 70.80078125, 74.92578125, 78.79296875, 82.91796875, 86.51953125, 90.64453125, 95.02734375, 21.95703125]
Peak usage: 95.02734375

```
## my results

`make run memory_limit=30M `
**output**:
```
{exited false false false true false 0 137  2023-04-25T18:41:59.356324616Z 2023-04-25T18:42:01.172699558Z <nil>}

```

2023-04-25 19:33 UTC, dmitry-mightydevops requested changes

2023-04-25 19:33 UTC, dmitry-mightydevops commented on chapter4/tests/t14/Dockerfile
> +COPY --from=build-env /usr/local/ /usr/local
no that is not safe. You copy a lot of system level files as well, not just python's files created by `pip install` on line 5.

2023-04-25 19:33 UTC, dmitry-mightydevops commented on chapter4/tests/t14/Dockerfile
> +FROM gcr.io/distroless/python3:debug
don't use debug for production

2023-04-25 19:33 UTC, dmitry-mightydevops commented on chapter4/tests/t14/Makefile
> +		docker run -m $(memory_limit) $(docker_image) || docker inspect -f '{{.State}}' $$(docker ps -lq); \
`docker ps -lq` is not safe approach in this example - use name  for the container and start docker run with `--rm` to kill it on restart. 

obtain state info via `docker inspect --format {{.State}} YOURNAME`

2023-04-26 17:47 UTC, darliiin commented on chapter4/tests/t14/Dockerfile
> +COPY --from=build-env /usr/local/ /usr/local
done

2023-04-26 17:48 UTC, darliiin commented on chapter4/tests/t14/Dockerfile
> +FROM gcr.io/distroless/python3:debug
done

2023-04-26 17:48 UTC, darliiin commented on chapter4/tests/t14/Makefile
> +		docker run -m $(memory_limit) $(docker_image) || docker inspect -f '{{.State}}' $$(docker ps -lq); \
done

2023-04-26 20:03 UTC, dmitry-mightydevops approved these changes

2023-04-27 03:48 UTC, merged