feat: t15 - chapter4-t15-tcpdump.sh
darliiin/devops-camp-2023 pull request #15
Opened 2023-04-27 10:35 UTC by darliiin

# Summary

## Test Task

- start nginx container
  ```sh
  docker run --rm --publish 8080:80 --name nginx nginx
  ```
- start another container with proper CAPs to debug TCP traffic in that container on port 80

Package your solution as a simple **tcpdump.sh** script and open PR.

**expected results:**

When you run your docker container, you should not get any output until you issue `curl` command against the port 80 in the nginx container

```sh
docker run --rm -it ...SOME OTHR ARGS
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
```

so:

```sh
curl  localhost:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

should display the following output in the debug container:

```sh
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
23:36:01.713827 IP d989164e5143.http > 172.17.0.1.45996: Flags [S.], seq 3710908605, ack 195269638, win 65160, options [mss 1460,sackOK,TS val 1157905495 ecr 842412289,nop,wscale 7], length 0
E..<..@.@............P.../..........XT.........
E.<W261.....
23:36:01.713944 IP d989164e5143.http > 172.17.0.1.45996: Flags [.], ack 79, win 509, options [nop,nop,TS val 1157905496 ecr 842412290], length 0
E..4.K@.@..S.........P.../.....T....XL.....
E.<X261.
23:36:01.714203 IP d989164e5143.http > 172.17.0.1.45996: Flags [P.], seq 1:239, ack 79, win 509, options [nop,nop,TS val 1157905496 ecr 842412290], length 238: HTTP: HTTP/1.1 200 OK
E..".L@.@..d.........P.../.....T....Y:.....
E.<X261.HTTP/1.1 200 OK
Server: nginx/1.23.4
Date: Wed, 19 Apr 2023 23:36:01 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 28 Mar 2023 15:01:54 GMT
Connection: keep-alive
ETag: "64230162-267"
Accept-Ranges: bytes

23:36:01.714247 IP d989164e5143.http > 172.17.0.1.45996: Flags [P.], seq 239:854, ack 79, win 509, options [nop,nop,TS val 1157905496 ecr 842412290], length 615: HTTP
E....M@.@............P.../.....T....Z......
E.<X261.<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

23:36:01.714538 IP d989164e5143.http > 172.17.0.1.45996: Flags [F.], seq 854, ack 80, win 509, options [nop,nop,TS val 1157905496 ecr 842412290], length 0
E..4.N@.@..P.........P.../.....U....XL.....
E.<X261.

```

## my results
`curl http://localhost:8080`

**output**:
```

tcpdump: data link type LINUX_SLL2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
10:21:08.655571 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [S], seq 2695623819, win 64240, options [mss 1460,sackOK,TS val 1674735017 ecr 0,nop,wscale 7], length 0
E..<@$@.@..r...........P............XT.........
c.m.........
10:21:08.655601 eth0  Out IP 172.17.0.2.80 > 172.17.0.1.50734: Flags [S.], seq 4051756909, ack 2695623820, win 65160, options [mss 1460,sackOK,TS val 734560938 ecr 1674735017,nop,wscale 7], length 0
E..<..@.@............P.....m........XT.........
+...c.m.....
10:21:08.655652 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [.], ack 1, win 502, options [nop,nop,TS val 1674735017 ecr 734560938], length 0
E..4@%@.@..y...........P.......n....XL.....
c.m.+...
10:21:08.656230 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [P.], seq 1:79, ack 1, win 502, options [nop,nop,TS val 1674735018 ecr 734560938], length 78: HTTP: GET / HTTP/1.1
E...@&@.@..*...........P.......n....X......
c.m.+...GET / HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.85.0
Accept: */*

10:21:08.656257 eth0  Out IP 172.17.0.2.80 > 172.17.0.1.50734: Flags [.], ack 79, win 509, options [nop,nop,TS val 734560939 ecr 1674735018], length 0
E..4..@.@.0..........P.....n........XL.....
+...c.m.
10:21:08.656643 eth0  Out IP 172.17.0.2.80 > 172.17.0.1.50734: Flags [P.], seq 1:239, ack 79, win 509, options [nop,nop,TS val 734560939 ecr 1674735018], length 238: HTTP: HTTP/1.1 200 OK
E.."..@.@./+.........P.....n........Y:.....
+...c.m.HTTP/1.1 200 OK
Server: nginx/1.23.4
Date: Thu, 27 Apr 2023 10:21:08 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 28 Mar 2023 15:01:54 GMT
Connection: keep-alive
ETag: "64230162-267"
Accept-Ranges: bytes

10:21:08.656698 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [.], ack 239, win 501, options [nop,nop,TS val 1674735019 ecr 734560939], length 0
E..4@'@.@..w...........P.......\....XL.....
c.m.+...
10:21:08.657135 eth0  Out IP 172.17.0.2.80 > 172.17.0.1.50734: Flags [P.], seq 239:854, ack 79, win 509, options [nop,nop,TS val 734560940 ecr 1674735019], length 615: HTTP
E.....@.@.-..........P.....\........Z......
+...c.m.<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

10:21:08.657180 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [.], ack 854, win 501, options [nop,nop,TS val 1674735019 ecr 734560940], length 0
E..4@(@.@..v...........P............XL.....
c.m.+...
10:21:08.657990 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [F.], seq 79, ack 854, win 501, options [nop,nop,TS val 1674735020 ecr 734560940], length 0
E..4@)@.@..u...........P............XL.....
c.m.+...
10:21:08.658085 eth0  Out IP 172.17.0.2.80 > 172.17.0.1.50734: Flags [F.], seq 854, ack 80, win 509, options [nop,nop,TS val 734560941 ecr 1674735020], length 0
E..4..@.@.0..........P..............XL.....
+...c.m.
10:21:08.658157 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [.], ack 855, win 501, options [nop,nop,TS val 1674735020 ecr 734560941], length 0
E..4@*@.@..t...........P............XL.....
c.m.+...
tcpdump: data link type LINUX_SLL2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
10:21:08.655571 eth0  In  IP 172.17.0.1.50734 > 172.17.0.2.80: Flags [S], seq 2695623819, win 64240, options [mss 1460,sackOK,TS val 1674735017 ecr 0,nop,wscale 7], length 0
E..<@$@.@..r...........P............XT.........
c.m.........
10:21:08.655601 eth0  Out IP 172.17.0.2.80 > 172.17.0.1.50734: Flags [S.], seq 4051756909, ack 2695623820, win 65160, options [mss 1460,sackOK,TS val 734560938 ecr 1674735017,nop,wscale 7], length 0
E..<..@.@............P.....m........XT.........
+...c.m.....
10:21:08.65 [...]

2023-04-28 20:41 UTC, dmitry-mightydevops approved these changes

2023-04-28 20:45 UTC, dmitry-mightydevops requested changes

2023-04-28 20:45 UTC, dmitry-mightydevops commented on chapter4/tests/t15/tcpdump.sh
> +docker run --rm -it --net=container:nginx alpine sh -c "apk add -q tcpdump && tcpdump -n -A -i any tcp port 80"
for future - use nixery
```
docker run --rm --privileged --pid container:heartbeat --network container:heartbeat -it --name privileged nixery.dev/shell/tcpdump tcpdump -n -A -i any tcp port 80
```

or use pre-packaged network debugging image https://github.com/nicolaka/netshoot

2023-04-29 06:34 UTC, darliiin commented on chapter4/tests/t15/tcpdump.sh
> +docker run --rm -it --net=container:nginx alpine sh -c "apk add -q tcpdump && tcpdump -n -A -i any tcp port 80"
I fixed it, made it using pre-packaged network debugging image, is that better?

2023-04-30 02:27 UTC, dmitry-mightydevops approved these changes

2023-04-30 02:27 UTC, dmitry-mightydevops commented on chapter4/tests/t15/tcpdump.sh
> +docker run --rm -it --net=container:nginx alpine sh -c "apk add -q tcpdump && tcpdump -n -A -i any tcp port 80"
@darliiin yes it's always better.

2023-04-30 05:36 UTC, merged