chapter5-t4-terraform2
darliiin/devops-camp-2023 pull request #20
Opened 2023-06-02 06:31 UTC by darliiin

# Summary

## Test Task

**that means utilizing terraform:**
- create mysql database
  - use random provider to generate random mysql admin password
  - export that password in outputs.tf
- create acm cert
- generate ssh key
  - do not store SSH key locally
  - do not push SSH key into your remote git repo, so add `.gitignore` properly to your file.
- create 2 ec2 instances
  - export instance_ids as list into your outputs.tf
- deploy wordpress using USERDATA of the EC2 instances
- create EFS instance and mount it in the EC2 instance via fsdata
  - export FS ID in the outputs.tf
- create ALB and target groups
  - export your ALB URL in the outputs.tf
- add Route53 record for your ALB URL
  - full record FQDN in the outputs.tf
- Use <https://developer.hashicorp.com/terraform/language/resources/provisioners/remote-exec> and <https://developer.hashicorp.com/terraform/language/resources/provisioners/connection>  with SSH KEY generated above to run any commands on the instance (such as if you need to run any SQL commands to update wordpress settings with proper domains)
  - no need to install any plugins/image gallery
  - your wordpress should work with just a demo post.
  - use random provider to generate random mysql admin password
  - export that password in outputs.tf
  

## Test calls

## test 1
curl https://test-student-user-exam.saritasa-camps.link
should output valid html content of the wordpress home

## test 2
curl https://test-student-user-exam.saritasa-camps.link/admin
should out admin login screen

## test 3
curl http://test-student-user-exam.saritasa-camps.link/
should timeout

## test 4
prove that both instances are joined in the load balancer by showing their nginx access logs output.

## Nuances of the implementation

- for DB password/Wordpress admin password use this: <https://registry.terraform.io/providers/hashicorp/random/latest/docs>
- for the DB / RDS use this module: <https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest>
- for the security group use this module: <https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest>
- for ec2 instance use this  module: <https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/latest>
- for efs use this module: <https://registry.terraform.io/modules/terraform-aws-modules/efs/aws/latest>
- for alb use this module: <https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest>
- for route53 records use this module: <https://registry.terraform.io/modules/terraform-aws-modules/route53/aws/latest>
- use any `data` providers offered by AWS terraform provider.
- to generate SSH Keys you can use this module <https://registry.terraform.io/modules/cloudposse/key-pair/aws/latest> or you can do bare atomic resources like the following example:

```hcl
resource "tls_private_key" "cluster" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "cluster" {
  key_name   = var.cluster_name
  public_key = tls_private_key.cluster.public_key_openssh
}

resource "local_sensitive_file" "ssh_private_key" {
  content              = tls_private_key.cluster.private_key_openssh
  filename             = "${path.cwd}/assets/private_keys/${var.cluster_name}.pem"
  file_permission      = "0600"
  directory_permission = "0700"
}

```
make sure your SSH keys are not pushed in your public repo, so create the following `.gitignore` file in the root of your git repository **before** the commit:

```sh
➜ cat .gitignore               
__pycache__
.git-crypt/
.idea/
.ssh/
.terraform/
.vscode
*.bak
*.pyc
*.tfstate
*.tfstate.backup
*.zip
.git_rev
*.pem
*.pub
*.log
assets/ssl
builds/
packer_cache
git-crypt-key

```

**Important**: Make sure your traffic is through the VPN. So reuse the same makefile I have. Use the same structure for folders as in this task. Implement only a single environment (`dev`)

## my results
https://dev-daria-nalimova-user-wp.saritasa-camps.link/index.php/sample-page/
https://dev-daria-nalimova-user-wp.saritasa-camps.link/wp-admin/

![Screenshot_20230602_113051](https://github.com/darliiin/devops-camp-2023/assets/117597862/db13f1e0-ccc6-4632-bc98-fb4efddef08a)

2023-06-05 00:39 UTC, dmitry-mightydevops requested changes

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/config.tf
> +}
when you create a new version of the application - always use latest versions of the modules and providers.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +locals {
move locals to locals.tf

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  random_string_array = [
not crystal clear why do you need 8 random strings? No comments no inline docs.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      source_security_group_id = module.wordpress_alb_sg.security_group_id
very good :)

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      cidr_blocks = "54.148.180.72/32"
that should never be hardcoded and should come with tfvars variables, where you clearly explain that this is your home IP addr or corp IP addr.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      cidr_blocks = "54.148.180.72/32"
use named `ssh-tcp` sg that is part of this module.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      to_port                  = 80
use named `http-80-tcp` rule

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      to_port                  = 80
see how it's used
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/3c405b18f5ffd09128b3a0c3e42bf0c8e9a3a3ad/examples/computed/main.tf#L29

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +#   │ instans             │
typo

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +module "ec2_instance" {
give reasonable name for your modules. ec2_instance is too generic.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  instance_type          = "t3.micro"
never hardcode stuff

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  subnet_id              = "subnet-06bf7d626cfb50b30"
never hardcode stuff
use `data` resources of the aws provider - to pull info about desired subnet per my lecture.
hardcoding - means HARD maintenance down the road.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +    random_pswd         = local.random_pswd,
random_pwd.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +module "ec2_instance" {
so name it like
module "wordpress_ec2_instance"

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  for_each = toset(var.instance_names)
should use `count`, not for_each. 
https://developer.hashicorp.com/terraform/language/meta-arguments/count

that count  - should be in the tfvars. In your case = 2.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  for_each = toset(var.instance_names)
Don't recreate the instance - learn how to "move" the state once the name(path) of the resource change.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +module "wordpress_rds_sg" {
break down your main.tf into
rds.tf
ec2.tf
security_groups.tf
acm.tf 
etc...
and define modules/resources in these files.

Don't make LONG main.tf with tons of modules/resources inside.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  identifier = "${var.environment}-${var.client}-rds"
define name properly via `https://github.com/cloudposse/terraform-null-label.git?ref=0.25.0` module.
don't interpolate strings to form the name this way.

If we decide to change the naming structue i.e. rds-client-environment - you will have hard time doing it.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  major_engine_version = "8.0"
never hardcode - that should come from your tfvars.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  backup_window      = "03:00-06:00"
never hardcode

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      to_port                  = 2049
use named rule

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  #   version                  = "4.17.2"
use proper version

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +  security_groups = [module.wordpress_alb_sg.security_group_id, "sg-0d10a167dff95ae61"]
don't hardcode. use data resources to pull info.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      subnet_id = "subnet-0c437405f83328b86"
use data resources to pull info from the vpc. Don't hardcode - this is not maintainable

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +      }
so what if you change count to 3? Your code would not work - find how to create terraform with dynamic number of targets.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +resource "aws_acm_certificate" "cert" {
export all acm related resources into acm.tf file

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +resource "aws_route53_record" "Aroute53" {
use underscore names for all resource names.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/main.tf
> +resource "aws_route53_record" "Aroute53" {
learn how to move the state once you change the name of the resource. `terraform mv`

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value = [module.ec2_instance["1"].id, module.ec2_instance["2"].id]
inflexible solution. What if you have 1 or 3 or 5 ec2 instances in the future. Lean how to use for/count or `*` operation to export ALL counts of module.ec2_instance.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +output "rout_name" {
typo.
use a better name for the output var.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userd.tpl
> +define('NONCE_SALT',       '${random_string_array[7]}');
not clean solution. Find a better one.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +variable "cache_vpc_tags" {
you're not using aws elasticache - so why `cache` prefix?

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Egress rule"
bad description. bad name. Impossible to understand what is it for - without reading the code and finding its use.
all your vars should be:
- semantic (name should tell you something)
- description should provide proper hints to the engineer why this var has been introduced, what it is used in/why.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
duplicated vars.

replace the solution with
`var.wordpress_instances_count = 2` and use it in your implementation

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
all your vars should be prefixed like
db_name
db_user
db_pass

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
etc

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
you should not have any ingress rules as vars. You should get all info needed when you have your resources created in the terraform code.

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +}
same issue as above

2023-06-05 00:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +}
your ec2 instances do not exists when you run the terraform apply for the first time.
your code should NOT imply multiple `terraform apply` runs to get to the finish state

```
terraform apply
```

should be called once and create all necessary resources/configuration from the first attempt.

2023-06-06 06:26 UTC, darliiin commented on chapter5/terraform/terraform/base/config.tf
> +}
done

2023-06-06 06:27 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +locals {
done

2023-06-06 06:27 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  random_string_array = [
comment added

2023-06-06 06:28 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +      cidr_blocks = "54.148.180.72/32"
done

2023-06-06 06:31 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +      to_port                  = 80
done

2023-06-06 06:31 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +#   │ instans             │
done

2023-06-06 06:31 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +module "ec2_instance" {
done

2023-06-06 06:32 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  instance_type          = "t3.micro"
corrected

2023-06-06 06:32 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  subnet_id              = "subnet-06bf7d626cfb50b30"
corrected

2023-06-06 06:32 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +    random_pswd         = local.random_pswd,
corrected

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  for_each = toset(var.instance_names)
corrected

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +module "wordpress_rds_sg" {
done

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  identifier = "${var.environment}-${var.client}-rds"
corrected

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  major_engine_version = "8.0"
corrected

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  backup_window      = "03:00-06:00"
corrected

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +      to_port                  = 2049
done

2023-06-06 06:33 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  #   version                  = "4.17.2"
corrected

2023-06-06 06:34 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +  security_groups = [module.wordpress_alb_sg.security_group_id, "sg-0d10a167dff95ae61"]
corrected

2023-06-06 06:34 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +      subnet_id = "subnet-0c437405f83328b86"
done

2023-06-06 06:34 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +      }
done

2023-06-06 06:34 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +resource "aws_acm_certificate" "cert" {
done

2023-06-06 06:35 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +resource "aws_route53_record" "Aroute53" {
corrected

2023-06-06 06:35 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +  value = [module.ec2_instance["1"].id, module.ec2_instance["2"].id]
done

2023-06-06 06:36 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +output "rout_name" {
corrected

2023-06-06 06:36 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +variable "cache_vpc_tags" {
corrected

2023-06-06 06:36 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "Egress rule"
done

2023-06-06 06:36 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
done

2023-06-06 06:36 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
done

2023-06-06 06:37 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
corrected

2023-06-06 06:37 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
corrected

2023-06-06 07:14 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
done

2023-06-06 08:14 UTC, darliiin commented on chapter5/terraform/terraform/base/userd.tpl
> +define('NONCE_SALT',       '${random_string_array[7]}');
Should I stop using an array?

2023-06-06 21:38 UTC, dmitry-mightydevops requested changes

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
remove this file from the PR pls

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
learn how to use and use splat * 
https://developer.hashicorp.com/terraform/language/expressions/splat

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id              = data.aws_subnets.wordpress.ids[2]
introduce a better way to reference the subnet, `ids[2]` is not very readable.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id              = data.aws_subnets.wordpress.ids[2]
ideally you need to have the data resource that will use proper filtering to return you an exact subnet you need for your deployment.

What if that data resource in future changes "indexes" as new subnet got available? and your [2] would become [3] in aws but not in your code - you will have downtime with the next apply.

So don't rely on INDEX values - they are mutating values and should not be trusted.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    efs_id              = local.efs_id
don't proxy values you get from the outputs of the modules. Use them right from the modules here.
i.e. rds endpoint should come from your module rds.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +    }
same issue with index values - find a better way to reference the subnets.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/locals.tf
> +  db_name_rds  = module.wordpress_rds.db_instance_name
don't proxy - you get no value. You don't "change/compute" the data from the modules (vs security group labels where you dynamically change the value). This will reduce readability of the code.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/locals.tf
> +}
cryptic. very cryptic.

Find a better way.

Nobody knows what random[7] is or meant to be.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value = [for i in range(var.wordpress_instances_count) : module.wordpress_ec2_instance[i].id]
use splat * of the terraform

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  version        = "5.9.0"
version should be right after the source. Your placement confuse other engineers to think you want to unstall mysql v5.9.0 which is not the case here. (readability issue)

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  password               = random_password.password.result
remove unnecessary empty lines.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "54.148.180.72/32"
no to hardcoding

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userd.tpl
> +define('NONCE_SALT',       '${random_string_array[7]}');
remember - your goal is to avoid using "mutating" data. LIST is a mutating object. What is in your code in [7] may become [6] in the future - which would result the rebuild as plan would detect the change of the data and will mark related resources into "update" or "recreate" mode.

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instance" "ec2_instances" {
why do you need this data resource?

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instance" "ec2_instances" {
I don't see it's used anywhere

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instance" "ec2_instances" {
go through all code and clean up stuff you don't need

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +instance_ami  = "ami-08333bccc35d71140"
add link to AMI in the GUI so we can clearly see what that is
document the full name of the AMI as inline comment

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +engine             = "wordpress"
very unsemantic name. Where is it used?

2023-06-06 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +db_port     = "3306"
prefixes.

2023-06-06 21:42 UTC, dmitry-mightydevops requested changes

2023-06-07 06:47 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +}
done

2023-06-07 06:47 UTC, darliiin commented on chapter5/terraform/terraform/base/main.tf
> +resource "random_string" "random" {
done

2023-06-07 06:48 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +db_port     = "3306"
done

2023-06-07 06:48 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +engine             = "wordpress"
done

2023-06-07 06:48 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +instance_ami  = "ami-08333bccc35d71140"
done

2023-06-07 06:49 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +engine             = "wordpress"
deleted

2023-06-07 06:49 UTC, darliiin commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_instance" "ec2_instances" {
deleted

2023-06-07 06:50 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
done

2023-06-07 06:50 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +}
done

2023-06-07 06:50 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +variable "engine" {
done

2023-06-07 06:50 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "54.148.180.72/32"
corrected

2023-06-07 06:51 UTC, darliiin commented on chapter5/terraform/terraform/base/rds.tf
> +  password               = random_password.password.result
done

2023-06-07 06:51 UTC, darliiin commented on chapter5/terraform/terraform/base/rds.tf
> +  version        = "5.9.0"
corrected

2023-06-07 06:51 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +  value = [for i in range(var.wordpress_instances_count) : module.wordpress_ec2_instance[i].id]
done

2023-06-07 06:51 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +    efs_id              = local.efs_id
done

2023-06-07 06:52 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = [for record in aws_route53_record.record : record.fqdn]
done

2023-06-07 11:04 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
deleted

2023-06-07 11:04 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id              = data.aws_subnets.wordpress.ids[2]
done

2023-06-07 11:05 UTC, darliiin commented on chapter5/terraform/terraform/base/efs.tf
> +    }
done

2023-06-07 11:05 UTC, darliiin commented on chapter5/terraform/terraform/base/locals.tf
> +  db_name_rds  = module.wordpress_rds.db_instance_name
done

2023-06-07 11:05 UTC, darliiin commented on chapter5/terraform/terraform/base/locals.tf
> +}
done

2023-06-07 19:52 UTC, dmitry-mightydevops commented
@darliiin you forget to remove DRAFT status from your PRs.

2023-06-07 19:55 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userd.tpl
> +define( 'DB_NAME', '${db_name_rds}' );
you used offset padding in lines 102-109. So use the same offsetting in 95-100

2023-06-07 20:01 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +db_family              = "mysql8.0"
sequence of values in this file does not match their order in the variables.tf

2023-06-07 20:01 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +/*
use simple `#` inline comments. no need the doc block

2023-06-07 20:17 UTC, dmitry-mightydevops requested changes
# Dasha - Better
Few changes.

a. Always convert to OPEN from DRAFT when you reopen the PR
b. Always add/remove labels depends on the status of  the PR
c. Re-request the review from reviewers rejected the previous version of the PR (right top red icon)

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +  validation_record_fqdns = values(aws_route53_record.record)[*].fqdn
good that you found `values` to convert map to list

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  version        = "5.9.0"
@darliiin not done.

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  version                             = "5.9.0"
version should be right below the source attr for every tf module

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +  │ unstances    │
typo. read your code before opening the PR.

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +  │ wordpress configuration variables    │
if it's wordpress config related below then vpc_tags should be prefixed.

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/alb.tf
> +      name             = local.labels.wordpress_alb_tg
sequence of attrs matters for readability
in http_listeners your order is
- 1. port
- 2. protocol
- 3. others

so do the same in 
```
target_groups = [
    {
        backend_port = 80
        backend_protocol = HTTP
        .... other attrs
    }
]
```


readability (semantic naming, sequence of attrs) matters in terraform and kubernetes, otherwise you will become a "YAML developer"

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +
don't use empty spaces

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +    # Authentication Unique Keys and Salts for wordpress
move such comment on the right side of the equation to keep consistent format of the code.

remove unnecessary empty lines.

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +
no need for empty line

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +  # File system
this comment does not provide any value to the reader.

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +  # Mount targets / security group
this comment does not provide an value to the reader.

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +  # Mount targets / security group
convert mount_targets

use 
```
for subnet in [data.aws_subnet.wordpress_subnet_a_zone, data.aws_subnet.wordpress_subnet_b_zone, data.aws_subnet.wordpress_subnet_c_zone]...
```

calculate keys for the map dynamically as well from the var `subnet` in the foreach above

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +output "password" {
password of what? rds? wordpress?
desc is vague

if rds - then prefix it properly and also use exported value from the rds module. That will improve readability of your code

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  value = aws_route53_record.A_route53.fqdn
all your resource names should be lowercase, no `A_something`

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "5.0.0"
your solution should always use the same version for all modules. Above 4.17.2 used. Here 5.0.0 is used. Be consistent

2023-06-07 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/userd.tpl
give this file a better name, it's not semantic.

2023-06-07 20:18 UTC, dmitry-mightydevops commented
@darliiin also you missed some of my comments in the hidden previous discussion that are NOT resolved. GITHUB hides them automatically if PR has too many open comments - so get a habit of opening ALL comments above to make sure they are all resolved.

Once resolved - write comment "Done"

2023-06-08 12:07 UTC, darliiin commented on chapter5/terraform/terraform/base/vpc.tf
> +}
done

2023-06-08 12:17 UTC, darliiin commented on chapter5/terraform/terraform/base/rds.tf
> +  version        = "5.9.0"
```
module "wordpress_rds" {
  source                              = "terraform-aws-modules/rds/aws"
  version                             = "5.9.0"
```

2023-06-08 12:18 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "54.148.180.72/32"
` ingress_with_cidr_blocks = [
    {
      rule        = "ssh-tcp"
      description = "Open ssh connection"
      cidr_blocks = var.office_ip
    }`

2023-06-08 12:19 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "54.148.180.72/32"
```
 ingress_with_cidr_blocks = [
    {
      rule        = "ssh-tcp"
      description = "Open ssh connection"
      cidr_blocks = var.office_ip
    }
```

2023-06-08 12:25 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +variable "wordpress_availability_zones" {
done

2023-06-08 12:26 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +variable "wordpress_wpconfig_random_count_lines" {
done

2023-06-08 12:27 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +variable "wordpress_wpconfig_count_characters" {
done

2023-06-08 12:38 UTC, darliiin commented on chapter5/terraform/terraform/base/rds.tf
> +  version                             = "5.9.0"
I transferred the version under the source.
need to specify the version for each module?

2023-06-08 12:38 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +  │ unstances    │
done

2023-06-08 12:40 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +  │ wordpress configuration variables    │
done

2023-06-08 12:42 UTC, darliiin commented on chapter5/terraform/terraform/base/alb.tf
> +      name             = local.labels.wordpress_alb_tg
done

2023-06-08 12:45 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +    # Authentication Unique Keys and Salts for wordpress
done

2023-06-08 12:46 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +
done

2023-06-08 12:49 UTC, darliiin commented on chapter5/terraform/terraform/base/efs.tf
> +  # File system
deleted

2023-06-08 12:49 UTC, darliiin commented on chapter5/terraform/terraform/base/efs.tf
> +  # Mount targets / security group
done

2023-06-08 12:49 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +output "password" {
done

2023-06-08 12:50 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +  value = aws_route53_record.A_route53.fqdn
done

2023-06-08 12:50 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "5.0.0"
done

2023-06-08 12:50 UTC, darliiin commented on chapter5/terraform/terraform/base/userd.tpl
done

2023-06-08 19:50 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/rds.tf
> +  version                             = "5.9.0"
yes each module should have a pinned version (otherwise every time you run `init` - the latest version would be downloaded and used which may lead to incompatibility at the attrs level - so always pin all external modules/providers with proper version)

2023-06-08 19:52 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +db_family              = "mysql8.0"
@darliiin ping

2023-06-08 20:01 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +output "password_for_db" {
your output vars should match your variables.
in your variables you have `db_....`, but here it's completely different

such naming would make the code harder to read and maintain.

naming - **matters!**

2023-06-08 20:01 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "4.17.2"
not done you always need to use LATEST version which is now 5.1
https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest

2023-06-08 20:01 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "5.0.0"
you should be using latest

2023-06-08 20:02 UTC, dmitry-mightydevops requested changes
need changes

2023-06-09 04:55 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +    random_pwd       = random_password.password_for_db.result
done

2023-06-09 04:55 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +    AUTH_KEY         = random_string.AUTH_KEY.result # Authentication Unique Keys and Salts for wordpress
done

2023-06-09 04:55 UTC, darliiin commented on chapter5/terraform/terraform/base/efs.tf
> +    subnet.availability_zone => {
done

2023-06-09 04:56 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +output "instance_id" {
done

2023-06-09 04:56 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +  value     = random_password.password_for_db.result
done

2023-06-09 04:56 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +output "password_for_db" {
done

2023-06-09 04:56 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +  version     = "4.17.2"
done

2023-06-09 20:14 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +db_family              = "mysql8.0"
not done

2023-06-09 20:17 UTC, dmitry-mightydevops requested changes
sequence of variables.tf and dev.tfvars do not match
![image](https://github.com/darliiin/devops-camp-2023/assets/70822710/7a0edd7d-f08b-4820-8dcc-6b890078feb1)

Pls go and compare in details. These small details matters in the long run and SIMPLIFY the maintenance - quite a LOT.

2023-06-09 20:17 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  sensitive   = true
sensitive should be always first attr in the output var - as it's important

2023-06-10 04:45 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +  sensitive   = true
done

2023-06-10 04:46 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +db_family              = "mysql8.0"
done

2023-06-10 21:00 UTC, dmitry-mightydevops commented
@darliiin invalid workflow for the PR

2023-06-10 21:01 UTC, dmitry-mightydevops requested changes
invalid workflow for re-opening the PR

2023-06-11 21:35 UTC, dmitry-mightydevops requested changes

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +output "record_name" {
`wordpress_fqdn` would be semantic

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_route53_record" "record" {
name `record` for the resource is not semantic - it's generic. If you put here validation records for the acm - then the resource name should be different.

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_route53_record" "a_type_route53" {
`a_type_route53` - is not semantic name, it's generic name.
like sayin
darya - is human. it contains minimum information to distinguish you from other humans.
female - is better
russian_female - is better
russian_female_in_ekb - is better as with each one it cuts a lot of "other generic" records from the pool.

Good naming allows you to understand why this resource was created without connecting in mind the other resources like alb to understand the purpose of it.

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_route53_record" "a_type_route53" {
once change the name - adjust all your outputs resources as well

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
now this file is beautifully structure and is **easy** to read. Thank you!

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  source                = "cloudposse/key-pair/aws"
all modules should be pinned to a specific version

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/alb.tf
> +  source             = "terraform-aws-modules/alb/aws"
all modules should be pinned to a specific version otherwise update in future may get your solution the downtime as the version (and behavior) may change.

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
> +  source                 = "terraform-aws-modules/ec2-instance/aws"
all modules should be pinned to a specific version otherwise update in future may get your solution the downtime as the version (and behavior) may change.

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +  source = "terraform-aws-modules/efs/aws"
all modules should be pinned to a specific version otherwise update in future may get your solution the downtime as the version (and behavior) may change.

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/efs.tf
> +    for subnet in [data.aws_subnet.wordpress_subnet_a_zone, data.aws_subnet.wordpress_subnet_b_zone, data.aws_subnet.wordpress_subnet_c_zone] :
beautify this code into multiline

2023-06-11 21:35 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/dev/dev.tfvars
> +environment = "dev"
env should be always 1st line in the file to make it clear the name for the reviewer. That is the only exception for the order of the vars to variables.tf

2023-06-11 21:38 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/ec2.tf
<img src="https://media3.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif"/>

2023-06-11 22:45 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +output "record_name" {
done

2023-06-11 22:45 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_route53_record" "record" {
done

2023-06-11 22:47 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_route53_record" "a_type_route53" {
done

2023-06-11 22:48 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +  source                = "cloudposse/key-pair/aws"
done

2023-06-11 22:48 UTC, darliiin commented on chapter5/terraform/terraform/base/alb.tf
> +  source             = "terraform-aws-modules/alb/aws"
done

2023-06-11 22:48 UTC, darliiin commented on chapter5/terraform/terraform/base/efs.tf
> +  source = "terraform-aws-modules/efs/aws"
done

2023-06-11 22:48 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +  source                 = "terraform-aws-modules/ec2-instance/aws"
done

2023-06-11 22:48 UTC, darliiin commented on chapter5/terraform/terraform/base/efs.tf
> +    for subnet in [data.aws_subnet.wordpress_subnet_a_zone, data.aws_subnet.wordpress_subnet_b_zone, data.aws_subnet.wordpress_subnet_c_zone] :
done

2023-06-11 22:49 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +environment = "dev"
done

2023-06-12 17:59 UTC, dmitry-mightydevops requested changes

2023-06-13 04:06 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +module "ssh_key_pair" {
done

2023-06-14 06:19 UTC, kseniyashaydurova commented
@darliiin Please choose correct base image, because it is unreal to check such a big amount of files in this PR

2023-06-14 06:43 UTC, kseniyashaydurova requested changes

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/acm.tf
> +data "aws_route53_zone" "zone_record" {
Let's have a separate file for `Route53` resources, because it is not clear that we should search it in acm.tf file

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/acm.tf
> +  name         = "saritasa-camps.link"
Please don't hardcode and move it to vars

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/acm.tf
> +    for dvo in aws_acm_certificate.cert.domain_validation_options : dvo.domain_name => {
1. Please add a separate variable `domain_name` (you can calculate it in locals or set in vars directly)
2. Bad name `dvo`, please find something more semantically clear

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/acm.tf
> +  zone_id = data.aws_route53_zone.zone_record.zone_id
use separate `domain_name` var here instead of this

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/alb.tf
> +        for i in range(var.wordpress_instances_count) : "my_target_${i + 1}" => {
bad name for targets - `my_target`

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/config.tf
> +    tags = {
You can add here tags from your `var.tags` variable and they would be auto added to all AWS resources (so you can remove `tags = var.tags` from all resources)

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +module "wordpress_instance_labels" {
Is it used somewhere?

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +resource "random_string" "auth_key" {
Let's try to create lots of randoms dynamically? And also lets always locate `random` above the resource where it is used

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/infra.auto.tfvars
> +tags = {
Move this to `aws` provider

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/locals.tf
> +    wordpress_acm    = join(module.wordpress_label.delimiter, [var.environment, var.client, "wp.saritasa-camps.link"])
Please add domain as separate `domain_name` var

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +    {
Why do we need this? Do we plan to connect from RDS to instance? No. Usually instances connect to RDS

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ingress_with_cidr_blocks = [
That won't work. Try it, you DB is not publicly available, so you wouldn't be able to connect to it through VPN (you should be at the same VPC to connect to private RDS)

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "0.0.0.0/0"
I think that RDS should allow outgoing connections to wordpress instances only

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +      protocol    = "tcp"
why TCP?

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +      protocol    = "tcp"
why TCP?

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +      from_port   = 443
No need to define ports, see this

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/43974e94067251ee464018288aa44862d0adba22/rules.tf#L72 

The same for below

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'DB_USER',         'admin' );
should also come from env vars

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "number of available wordpress instances"
```suggestion
  description = "number of desired wordpress instances"
```

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/variables.tf
> +  │ env=specific configuration variables          │
```suggestion
  │ env-specific configuration variables          │
```

2023-06-14 06:43 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_availability_zones = ["us-east-2a", "us-east-2b"]
Why 2c is not available?

2023-06-14 07:24 UTC, roman-mightydevops requested changes

2023-06-14 07:24 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/outputs.tf
> +  description = "Fqdn of the record"
Please add correct capitalization in descriptions, for sake of readability. Abbreviations, especially - Fqdn looks like a nonsense at first glance.

2023-06-15 08:42 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +data "aws_route53_zone" "zone_record" {
done

2023-06-15 08:43 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +  name         = "saritasa-camps.link"
done

2023-06-15 08:43 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +    for dvo in aws_acm_certificate.cert.domain_validation_options : dvo.domain_name => {
done

2023-06-15 08:44 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +  zone_id = data.aws_route53_zone.zone_record.zone_id
done

2023-06-15 08:44 UTC, darliiin commented on chapter5/terraform/terraform/base/alb.tf
> +        for i in range(var.wordpress_instances_count) : "my_target_${i + 1}" => {
done

2023-06-15 08:56 UTC, darliiin commented on chapter5/terraform/terraform/base/config.tf
> +    tags = {
done

2023-06-15 08:57 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +module "wordpress_instance_labels" {
done

2023-06-16 04:58 UTC, darliiin commented on chapter5/terraform/terraform/base/infra.auto.tfvars
> +tags = {
done

2023-06-16 04:58 UTC, darliiin commented on chapter5/terraform/terraform/base/locals.tf
> +    wordpress_acm    = join(module.wordpress_label.delimiter, [var.environment, var.client, "wp.saritasa-camps.link"])
done

2023-06-16 04:58 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +    {
done

2023-06-16 04:59 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ingress_with_cidr_blocks = [
done

2023-06-16 04:59 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = "0.0.0.0/0"
done

2023-06-16 04:59 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      protocol    = "tcp"
done

2023-06-16 04:59 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      protocol    = "tcp"
done

2023-06-16 05:00 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      from_port   = 443
done

2023-06-16 05:00 UTC, darliiin commented on chapter5/terraform/terraform/base/userdata.tpl
> +define( 'DB_USER',         'admin' );
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "number of available wordpress instances"
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +  │ env=specific configuration variables          │
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_availability_zones = ["us-east-2a", "us-east-2b"]
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +  name         = "saritasa-camps.link"
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +resource "aws_acm_certificate_validation" "certificate" {
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ]
done

2023-06-16 05:01 UTC, darliiin commented on chapter5/terraform/terraform/base/outputs.tf
> +  description = "Fqdn of the record"
done

2023-06-16 07:09 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +resource "random_string" "auth_key" {
done

2023-06-19 04:26 UTC, kseniyashaydurova requested changes

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +  ssh_public_key_path   = "${path.cwd}/assets/private_keys"
Don't see this path in .gitignore

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/alb.tf
> +  target_groups = [
Do we need this target group if we have no listener for 80 port?

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/locals.tf
> +    domain_name      = join(module.wordpress_label.delimiter, [var.environment, var.client, "wp.saritasa-camps.link"])
This should come from vars `wp.saritasa-camps.link`

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/alb.tf
> +      backend_port     = 80
Do we need to allow to connect to instances on 80 port? As I understood task - no

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_subnet" "wordpress_subnet_a_zone" {
Is it possible to create dynamic data for aws subnets with `for_each`? Can you please try?

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/dev/dev.tfvars
> +office_ip = "54.148.180.72/32"
Let's make it flexible as list of ips

2023-06-19 04:26 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
Can you use these zones in your `base/vpc.tf` to get subnets data?

2023-06-19 07:52 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
done

2023-06-19 07:52 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +office_ip = "54.148.180.72/32"
done

2023-06-19 07:52 UTC, darliiin commented on chapter5/terraform/terraform/base/vpc.tf
> +data "aws_subnet" "wordpress_subnet_a_zone" {
done

2023-06-19 07:53 UTC, darliiin commented on chapter5/terraform/terraform/base/locals.tf
> +    domain_name      = join(module.wordpress_label.delimiter, [var.environment, var.client, "wp.saritasa-camps.link"])
done

2023-06-19 08:26 UTC, darliiin commented on chapter5/terraform/terraform/base/alb.tf
> +  target_groups = [
instances should only run on port 80
so 443 won't work

2023-06-19 08:30 UTC, darliiin commented on chapter5/terraform/terraform/base/alb.tf
> +      backend_port     = 80
instances only work on port 80

2023-06-19 10:11 UTC, roman-mightydevops approved these changes

2023-06-19 16:07 UTC, roman-mightydevops commented on chapter5/terraform/terraform/base/acm.tf
> +  depends_on = [aws_route53_record.acm_record]
You don't need `depends_on` statement since you already have a reference to this resource. Terraform docs recommend to not use it unless you have to.
https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on#processing-and-planning-consequences

2023-06-20 08:09 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id = data.aws_subnet.wordpress_subnets[var.subnet_availability_zones[0]].id
This looks not that nice:

1. Indent
2. You hard coded  subnet az, so all instances would only in 0 AZ and there is no way to change it. Lets choose dynamically with https://developer.hashicorp.com/terraform/language/functions/element (i.e. you can use `count` as `index`) So then we will have instances in different AZs

2023-06-20 08:09 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = var.ip_list[0]
Why do you hard coded only 0 ip address? What about others? Needs to make it work with other ip addresses too

2023-06-20 08:09 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/dev/dev.tfvars
> +domain_name = "wp.saritasa-camps.link"
What about adding it to `infra-auto.tfvars`?

2023-06-20 08:09 UTC, kseniyashaydurova commented on chapter5/terraform/terraform/dev/dev.tfvars
> +wordpress_availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
I don't see that you used it in your vpc.tf file. You created a new variable instead `subnet_availability_zones`. I meant that you can reuse it

2023-06-20 09:35 UTC, darliiin commented on chapter5/terraform/terraform/base/acm.tf
> +  depends_on = [aws_route53_record.acm_record]
done

2023-06-20 09:36 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +variable "subnet_availability_zones" {
done

2023-06-20 09:36 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +  description = "tail domain name"
done

2023-06-20 09:37 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      cidr_blocks = var.ip_list[0]
done

2023-06-20 09:37 UTC, darliiin commented on chapter5/terraform/terraform/dev/dev.tfvars
> +domain_name = "wp.saritasa-camps.link"
done

2023-06-20 10:15 UTC, darliiin commented on chapter5/terraform/terraform/base/ec2.tf
> +  subnet_id = data.aws_subnet.wordpress_subnets[var.subnet_availability_zones[0]].id
done

2023-06-20 21:39 UTC, dmitry-mightydevops requested changes

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/config.tf
> +    aws = "~> 5.1.0"
all providers have to have defined:
- source
- version 

like `random` provider, otherwise tflint will error out
https://github.com/terraform-linters/tflint

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ingress_with_cidr_blocks = [
instead making it a list with `for` - make 
```
cidr_blocks = join(",", var.allowed_ssh_ips)
```

see this
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/43974e94067251ee464018288aa44862d0adba22/examples/complete/main.tf#L82

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      description              = "Open all ipv4 connection"
if you set desc here make one above as well

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      description              = "Open all ipv4 connection"
be consistent

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/security_groups.tf
> +      rule        = "http-80-tcp"
why alb allows 80?

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  default     = [
prefer all defaults to be defined in the infra.auto.tfvars rather than in the variables.tf

2023-06-20 21:39 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each = toset(var.wordpress_availability_zones)
you don't benefit from this foreach as you get ALL

```
wordpress_availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
```

so find a way to work without the foreach

2023-06-21 00:59 UTC, darliiin commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each = toset(var.wordpress_availability_zones)
but i need all subnets since i use them for efs

2023-06-21 01:09 UTC, darliiin commented on chapter5/terraform/terraform/base/config.tf
> +    aws = "~> 5.1.0"
done

2023-06-21 01:09 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +  ingress_with_cidr_blocks = [
done

2023-06-21 01:09 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      description              = "Open all ipv4 connection"
done

2023-06-21 01:10 UTC, darliiin commented on chapter5/terraform/terraform/base/security_groups.tf
> +      rule        = "http-80-tcp"
done

2023-06-21 01:12 UTC, darliiin commented on chapter5/terraform/terraform/base/variables.tf
> +  default     = [
done
in which block should I place `wordpress_random_wpconfig_secrets` in variables
wp-config.php or env-specific configuration variables

2023-06-22 02:52 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/variables.tf
> +  default     = [
@darliiin you did it right in the infra.auto.tfvars

2023-06-22 02:55 UTC, dmitry-mightydevops commented on chapter5/terraform/terraform/base/vpc.tf
> +  for_each = toset(var.wordpress_availability_zones)
I understand, but this a design flaw. Your increase the complexity of the resource just so that you can use by index or key in the other resource, which is harder to maintain down the road.

This data block  will return you all subnets if it's defined like

```hcl
data "aws_subnet" "wordpress_subnets" {
  vpc_id            = data.aws_vpc.target.id
}
```

so you will get a list of 3 subnets under indexes 0, 1, 2. So you should use that data.

2023-06-22 02:56 UTC, dmitry-mightydevops approved these changes
Dasha,

this pr is **CONDITIONALLY** Approved (at the code level).

Now I need a video with
- terraform destrory
- terraform apply
- curl queries (or real browser GUI) for the app

Use OBStudio in linux. It can record entire screen with voice. If DNS propagation takes time - pause OBS and then continue when DNS resolves.

2023-06-22 02:57 UTC, dmitry-mightydevops commented
When you finish the video - upload it to google drive and share the link with us.

2023-06-22 15:25 UTC, darliiin commented
video with

- terraform destrory
- terraform apply
- browser GUI for the app

https://drive.google.com/file/d/1_WI2xy77SfuRVtsz5nJlw6ZZXEQkWlEA/view

2023-06-27 03:23 UTC, kseniyashaydurova approved these changes

2023-06-28 19:50 UTC, dmitry-mightydevops commented
@darliiin 
pls terminate all resources in the AWS Camp account created
- via terraform
- or manually in early tasks:
  - load-balancers
  - certificates
  - security groups
  - ec2 instances
  - rds instances
  - elasticache etc

2024-03-27 10:03 UTC, merged