chapter5-t3-terraform1
darliiin/devops-camp-2023 pull request #21
Opened 2023-06-04 18:57 UTC by darliiin

# Summary

## Test Task

- fix the problem with existing implementation of modules. They're duplicating functionality of downloading the image and starting the container. So export that functionality into generic module stored in `_modules/container` and reuse it in the modules `nginx` and `redis`
  - since the nginx implementation has **local-exec** provisioner, please build a proper way to delete generated index.html pages, yet using the "docker" module you will create above.
- open PR when ready

2023-06-05 10:59 UTC, kseniyashaydurova commented
@darliiin Please always add link to original task (so it would be easier for me and @roman-mightydevops to understand, what is needed). Please add this link to your PR description - https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter6%20-%20terraform/l4%20-%20environments/environments.md

2023-06-05 11:53 UTC, roman-mightydevops requested changes

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/delete.sh
> +folder="${SCRIPT_DIR}/../../../dev"
Modules should always be generic. This works only for dev folder, but what if I add another environment?

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +     working_dir = path.module
```suggestion
    working_dir = path.module
```
use `terraform fmt`

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  }
This makes module not reusable, but they supposed to be. Move this check out of it.

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  #   }
Why is it commented out?

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/config.tf
> +    }
I believe it's redundant. But haven't tried to run - how do I run it, by the way? 🤔

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  provisioner "local-exec" {
You need a destroy provisioner too

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/variables.tf
> +    error_message = "Container name should be prefixed with saritasa-devops-camps-2023-"
Same as for container module.

2023-06-05 11:53 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/_modules/redis/config.tf
> +    }
Same as for nginx module

2023-06-05 11:54 UTC, kseniyashaydurova requested changes

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/config.tf
> +  required_version = ">= 1.4.0"
Please always use latest packages versions and update `terraform`, `docker` versions here

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/delete.sh
> +#!/bin/bash
Please always add docs for such kind of things like scripts and etc with explanation what it does and why it is needed and when it is used

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +resource "docker_image" "container" {
Bad name for `docker_image` resource, should be `image`

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +     working_dir = path.module
Please improve indents

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Value of the name for the Docker container"
```suggestion
  description = "Docker image name"
```

P.S. let's add a separate variable `container_image_tag`, so in you main.tf you will have
```
resource "docker_image" "container" {
  name         = "${var.container_image}:${container_image_tag}"
  keep_locally = var.container_image_keep_locally
}
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Value of the name for the Docker container"
Let's use just:

```suggestion
  description = "Docker container name"
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Value of the name for the Docker container"
Wrong description

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  default = {
That is rather strange that you have a common `container` module, but by default you hard coded `redis` ports, let's make this field required and define it as object - https://developer.hashicorp.com/terraform/language/values/variables#declaring-an-input-variable

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  #   validation {
Let's remove it if it is not used

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Path to volume host"
```suggestion
  description = "Path to volume on host (local machine)"
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Path to volume container"
```suggestion
  description = "Path to volume inside container"
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +
Too many empty lines at the end

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +  ports {
Docker allows to define multiple pairs of `ports` (external and internal) as well as `volumes`, but your module - not. It allows to define only 1 pair, lets improve it to allow adding more pairs dynamically? https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/config.tf
> +terraform {
The same as for config.tf in module

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/config.tf
> +  required_providers {
Please also leave here only providers you really use inside this module

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/config.tf
> +    docker = {
It looks like you can omit `docker` provider here, because it would be added from your submodule

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +variable "container_image" {
I suggest to remove `container` prefix everywhere in variables of `container` module, because it is clear in `container` module from it name

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  volumes_container_path = "/usr/share/nginx/html"
Let;s also move this to env variables

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/locals.tf
> +locals {
I think there is no need in having separate `locals.tf` file , let's move this local var calculation above your `null_resource` in main.tf?
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/outputs.tf
> +  value       = substr(module.nginx.container_id, 0, 12)
You have a `container_id_short` output in your `container` module, no need to make `substr` here

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  container_ports = {
```suggestion
  container_ports = var.container_ports
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/nginx/variables.tf
> +  type        = map(any)
Please do the same updates for this var that I asked for `container` module

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/redis/config.tf
> +terraform {
The same as above

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/redis/main.tf
> +  container_ports = {
```suggestion
  container_ports = var.container_ports
```

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/redis/outputs.tf
> +output "container_id_short" {
the same as above

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +variable "container_ports" {
The same as above, please use `object` instead of map

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +    error_message = "Container internal port should be less 1000 and external above or equal to 8000"
Doesn't look like this is correct error message

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/config.tf
> +terraform {
the same as above

2023-06-05 11:54 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/main.tf
> +  count  = var.use_redis ? 1 : 0
Why there is no similar functionality for nginx?

2023-06-06 10:37 UTC, darliiin commented on chapter5/tests/t3/Makefile
> +include .makerc
done

2023-06-06 11:55 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/config.tf
> +  required_version = ">= 1.4.0"
done

2023-06-06 11:59 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/delete.sh
> +#!/bin/bash
done

2023-06-06 12:05 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Value of the name for the Docker container"
done

2023-06-06 12:07 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Value of the name for the Docker container"
done

2023-06-06 12:10 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  #   validation {
done

2023-06-06 12:11 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Path to volume host"
done

2023-06-06 12:12 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Path to volume container"
done

2023-06-06 12:13 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/config.tf
> +terraform {
done

2023-06-07 13:57 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  }
done

2023-06-07 13:59 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/config.tf
> +    }
deleted

2023-06-07 13:59 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/config.tf
> +    }
deleted

2023-06-07 14:01 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/config.tf
> +    docker = {
done

2023-06-09 05:14 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +     working_dir = path.module
done

2023-06-09 11:28 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  default = {
done

2023-06-09 11:29 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +resource "docker_image" "container" {
done

2023-06-09 11:45 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/variables.tf
> +  type        = map(any)
done

2023-06-09 11:45 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/config.tf
> +terraform {
done

2023-06-09 11:45 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +variable "container_ports" {
done

2023-06-09 11:46 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +    error_message = "Container internal port should be less 1000 and external above or equal to 8000"
done

2023-06-12 06:56 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  provisioner "local-exec" {
done

2023-06-12 06:56 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +     working_dir = path.module
deleted

2023-06-12 06:56 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  description = "Value of the name for the Docker container"
done

2023-06-12 06:57 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +variable "container_image" {
done

2023-06-12 06:57 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  volumes_container_path = "/usr/share/nginx/html"
done

2023-06-12 06:57 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/locals.tf
> +locals {
done

2023-06-12 06:57 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/outputs.tf
> +  value       = substr(module.nginx.container_id, 0, 12)
deleted

2023-06-12 06:58 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/outputs.tf
> +output "container_id_short" {
done

2023-06-12 07:00 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +  ports {
need to concatenate volumes_host_path and volumes_container_path into an object?

2023-06-12 07:01 UTC, darliiin commented on chapter5/tests/t3/terraform/base/main.tf
> +  count  = var.use_redis ? 1 : 0
in progress

2023-06-12 07:48 UTC, darliiin commented on chapter5/tests/t3/terraform/base/main.tf
> +  count  = var.use_redis ? 1 : 0
done

2023-06-14 06:04 UTC, kseniyashaydurova requested changes

2023-06-14 06:04 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/outputs.tf
> +  value = var.use_nginx ? {
Why not just like this?

```
value = var.use_nginx ? module.nginx : {}
```

2023-06-14 06:04 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/outputs.tf
> +  value = var.use_redis ? {
The same as above

2023-06-14 06:04 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/variables.tf
> +  description = "Do you need to speed up the perf using nginx?"
please update description, `nginx` doesn't speed up anything

2023-06-14 06:04 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/variables.tf
> +    container_name  = optional(string)
You can do just like this here
```
container_name = optional(string, null)
```

So it will set `null` by default and you don't need below stuff in nginx module

```
var.use_nginx ? (var.nginx.container_name != "" ? var.nginx.container_name : null) : null
```

2023-06-14 06:04 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/base/variables.tf
> +    container_name  = optional(string)
The same is related to redis

2023-06-14 06:13 UTC, kseniyashaydurova commented on chapter5/tests/t3/terraform/_modules/container/main.tf
> +  ports {
Yes, let's do the same logic for volumes too

2023-06-14 06:18 UTC, kseniyashaydurova commented
also there are errors on execution
![image](https://github.com/darliiin/devops-camp-2023/assets/26448672/c5982cca-afd6-4939-8c8d-f51c6592b370)

2023-06-14 12:01 UTC, roman-mightydevops reviewed
Approved as soon as you resolve Kseniya's conversations

2023-06-14 15:30 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/config.tf
> +      version = "~> 3.0.1"
done

2023-06-14 15:31 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  type        = string
done

2023-06-14 15:31 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +    command = "mkdir ../../${var.environment} && cat > ../../${var.environment}/index.html  <<EOL\n${local.rendered_index_html}\nEOL"
deleted

2023-06-14 15:31 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +    path = "../../${var.environment}"
deleted

2023-06-14 15:31 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/variables.tf
> +  description = "Value of the name for the Docker container"
done

2023-06-14 15:32 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/variables.tf
> +  description = "Value of the name for the Docker container"
done

2023-06-14 15:32 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/variables.tf
> +  description = "Value of the tag for the Docker container"
done

2023-06-14 15:32 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/main.tf
> +  ports              = var.container_ports
done

2023-06-14 15:33 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +  description = "Value of the tag for the Docker container"
done

2023-06-14 15:33 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +  description = "Value of the name for the Docker container"
done

2023-06-14 15:33 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/variables.tf
> +}
done

2023-06-14 15:33 UTC, darliiin commented on chapter5/tests/t3/terraform/base/main.tf
> +  container_name               = var.use_redis ? var.redis.container_name : null
done

2023-06-14 15:34 UTC, darliiin commented on chapter5/tests/t3/terraform/base/outputs.tf
> +  value = var.use_redis ? {
done

2023-06-15 06:30 UTC, roman-mightydevops approved these changes

2023-06-15 06:35 UTC, roman-mightydevops commented on chapter5/tests/t3/terraform/base/outputs.tf
> +#   } : {}
Remove commented lines

2023-06-19 04:34 UTC, kseniyashaydurova approved these changes

2023-06-19 04:48 UTC, kseniyashaydurova requested changes
When I enable redis
![image](https://github.com/darliiin/devops-camp-2023/assets/26448672/100dade0-5a4d-4c4b-9bc1-3efaa288a7a4)

2023-06-20 21:49 UTC, dmitry-mightydevops requested changes

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  environment = var.environment
prefer to put less important attrs at the end of the module whith always
- tags
- depends_on being latest

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +}
convert your solution when image and tag being a single variable and then use terraform functions to extract that information, i.e. nginx:1.21 etc

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  default     = false
prefer to have all defaults in the infra.auto.tfvars

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +locals {
put locals above the resources/modules where they're used or extract them all into locals.tf

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +    command = "mkdir ../../${var.environment} && cat > ../../${var.environment}/index.html  <<EOL\n${local.rendered_index_html}\nEOL"
use terraform `path` to get proper address.
https://developer.hashicorp.com/terraform/language/expressions/references#filesystem-and-workspace-info

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +    path = "../../${var.environment}"
use https://developer.hashicorp.com/terraform/language/expressions/references#filesystem-and-workspace-info

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/redis/main.tf
> +  environment = var.environment
move down - they should attract least attention when we read the code.

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/base/main.tf
> +  environment = var.environment
here you did it correctly

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/base/main.tf
> +  container_volumes = [
reduce number of lines are you have a single element in the list i.e.
```
container_volumes = [{
  volumes_host_path = ...
  volumes_container_path = ...
}]
```

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/base/main.tf
> +  container_volumes = []
that should come from your tfvars, not hardcoded.

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/base/main.tf
> +      volumes_container_path = var.nginx.volumes_container_path
that should come from your tfvars

2023-06-20 21:49 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/dev/dev.tfvars
> +  tag            = "latest"
convert into single attr, like nginx:latest and then use tf functions to get the desired part as needed.

2023-06-21 01:19 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +}
i.e. return the original solution? I separated the image and the tag as Ksenia said

2023-06-21 02:20 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +  environment = var.environment
done

2023-06-21 02:20 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +}
done

2023-06-21 02:21 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +locals {
done

2023-06-21 02:21 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +    command = "mkdir ../../${var.environment} && cat > ../../${var.environment}/index.html  <<EOL\n${local.rendered_index_html}\nEOL"
done

2023-06-21 02:21 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/nginx/main.tf
> +    path = "../../${var.environment}"
done

2023-06-21 02:26 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/redis/main.tf
> +  environment = var.environment
done

2023-06-21 02:26 UTC, darliiin commented on chapter5/tests/t3/terraform/base/main.tf
> +  container_volumes = [
done

2023-06-21 02:27 UTC, darliiin commented on chapter5/tests/t3/terraform/base/main.tf
> +  container_volumes = []
done

2023-06-21 02:27 UTC, darliiin commented on chapter5/tests/t3/terraform/dev/dev.tfvars
> +  tag            = "latest"
done

2023-06-21 02:28 UTC, darliiin commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +  default     = false
done

2023-06-21 02:43 UTC, darliiin commented on chapter5/tests/t3/terraform/base/main.tf
> +      volumes_container_path = var.nginx.volumes_container_path
If I understood correctly, calling functions or using other variables is not supported inside the definition of variables in Terraform
so I can't move "${abspath(path.root)}/../../${var.environment}" to variables

2023-06-22 02:59 UTC, dmitry-mightydevops commented on chapter5/tests/t3/terraform/_modules/container/variables.tf
> +}
ok then keep as is, just 2+2 = 1+3. Same outcome. I personally prefer less vars to be defined

2023-06-22 03:32 UTC, dmitry-mightydevops approved these changes

2023-06-23 07:39 UTC, merged