feat: t4 - chapter2-l2-t4-files-no-extensions.sh
darliiin/devops-camp-2023 pull request #3
Opened 2023-03-30 13:27 UTC by darliiin

**Summary
Test Task**

Script should get a folder as an argument and return all files (including in the nested directories) but without the extension

**name the file**: `chapter2-l2-t4-files-no-extensions.sh`

**example of the call:**

./chapter2-l2-t4-files-no-extensions.sh ~/tmp/bazel

```
/tmp/bazel/tools/objc/dummy
/tmp/bazel/third_party/zlib/zutil
/tmp/bazel/third_party/zlib/uncompr
/tmp/bazel/third_party/zlib/trees
/tmp/bazel/third_party/zlib/test/minigzip
/tmp/bazel/third_party/zlib/test/infcover
/tmp/bazel/third_party/zlib/test/example
/tmp/bazel/third_party/zlib/inftrees

```

**my results**
`./chapter2-l2-t4-files-no-extensions.sh ~/Загрузки/a`
**output:**
`repos/iss-kubernetes-aws-deploy-key
repos/kustomization
repos/iss-kubernetes-aws-deploy-key
repos/iss-backend-deploy-key
repos/iss-frontend-deploy-key
repos/iss-backend-deploy-key
repos/iss-frontend-deploy-key
`

2023-04-14 04:44 UTC, kseniyashaydurova requested changes

2023-04-14 04:44 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
It still seems that something works incorrectly here
![image](https://user-images.githubusercontent.com/26448672/231943373-58d32415-676d-4b9d-98cd-d204e5b08196.png)

![image](https://user-images.githubusercontent.com/26448672/231943546-550ef771-6a52-43d2-8858-7d39d99a1c51.png)

2023-04-14 04:44 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    # if the file is hidden, then display the file name
```suggestion
    # if the file is dotfile
```

2023-04-14 04:44 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    [[ $(echo "$file" | grep -o "\." | wc -l) -eq 0 ]]; then
Please move condition to the same line where `elif`, it is more common style of conditions, the same for below

2023-04-14 09:55 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    [[ $(echo "$file" | grep -o "\." | wc -l) -eq 0 ]]; then
done

2023-04-14 09:55 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    # if the file is hidden, then display the file name
done

2023-04-14 09:55 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
done

2023-04-19 09:30 UTC, kseniyashaydurova requested changes
:smiling_face_with_tear:

2023-04-19 09:30 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
Still doesn't work, you have the same problem as in 5th task
![image](https://user-images.githubusercontent.com/26448672/233032490-702dc38e-3e83-4c32-aa8c-95a4da1bf5b8.png)

2023-04-19 12:35 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
done

2023-04-26 08:51 UTC, roman-mightydevops approved these changes

2023-04-26 08:51 UTC, roman-mightydevops commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    [[ $(echo "$file" | grep -o "\." | wc -l) > 1 ]]; then
```suggestion
    [[ $(echo "$file" | grep -o "\." | wc -l) -gt 1 ]]; then
```

2023-04-30 07:02 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +    [[ $(echo "$file" | grep -o "\." | wc -l) > 1 ]]; then
done

2023-05-03 02:33 UTC, kseniyashaydurova requested changes

2023-05-03 02:33 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +      if [[ ($(echo "$file_name" | grep -o "\." | wc -l) -ne 1) || \
You do `$(echo "$file_name" | grep -o "\." | wc -l)` command lots of time, I think you can either move it to separate function or calculate it before your block with `if` conditions and save it to a separate variable (after the 12th line)

2023-05-03 19:52 UTC, darliiin commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +      if [[ ($(echo "$file_name" | grep -o "\." | wc -l) -ne 1) || \
done

2023-06-05 05:37 UTC, kseniyashaydurova approved these changes

2023-06-05 05:45 UTC, merged