feat: t6 - chapter2-l2-t6-get-file-unique-dirs.sh
darliiin/devops-camp-2023 pull request #5
Opened 2023-03-30 14:12 UTC by darliiin

**Summary**
**Test task**
t6 - get only dirs of the files
Script should get a folder as an argument and return a list of unique directories of all files (including in the nested directories). only -f option is allowed for the use of find command, i.e.: find /tmp -type f. Which should find all files in all nested dirs and then process the output by using expansion.

name the file: `chapter2-l2-t6-get-file-unique-dirs.sh`

**example of the call:**

`./chapter2-l2-t6-get-file-unique-dirs.sh ~/tmp`
```

/tmp/setguid
/tmp/bazel/tools/objc
/tmp/bazel/third_party/zlib
/tmp/bazel/third_party/zlib/test
/tmp/bazel/third_party/zlib
/tmp/bazel/third_party/zlib/examples
/tmp/bazel/third_party/zlib
/tmp/bazel/third_party/zlib/contrib/untgz
/tmp/bazel/third_party/zlib/contrib/testzlib
/tmp/bazel/third_party/zlib/contrib/puff

```
**my result**
`./chapter2-l2-t6-get-file-unique-dirs.sh ~/Загрузки/a
`
**output**
`/home/darlin/Загрузки/a/foto/photo_2023-03-20_16-00-58.jpg
/home/darlin/Загрузки/a/Maven_spring_demo.zip
/home/darlin/Загрузки/a/ideaIU-2022.3.3.tar.gz
/home/darlin/Загрузки/a/google-chrome-stable_current_amd64.deb
/home/darlin/Загрузки/a/2
/home/darlin/Загрузки/a/1
/home/darlin/Загрузки/a/3
/home/darlin/Загрузки/a/dariyanalimova.p12
`

2023-04-14 13:55 UTC, darliiin commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +#Checking the number of arguments passed
done

2023-04-14 13:55 UTC, darliiin commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +#!/bin/bash
done

2023-04-19 09:44 UTC, kseniyashaydurova commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +#Checking the number of arguments passed
Output is still incorrect
![image](https://user-images.githubusercontent.com/26448672/233036217-4e666cac-18cb-4b5b-bb8b-b2bc7ecd531e.png)

2023-04-19 09:44 UTC, kseniyashaydurova requested changes
Output is still incorrect 
![image](https://user-images.githubusercontent.com/26448672/233036273-93d79479-dd84-439c-8c70-d6c6fbdb0490.png)

2023-04-26 09:02 UTC, roman-mightydevops approved these changes

2023-05-03 02:35 UTC, kseniyashaydurova approved these changes

2023-05-03 03:19 UTC, merged