feat: t7 - chapter2-l2-t7-get-unique-files.sh
darliiin/devops-camp-2023 pull request #6
Opened 2023-03-30 14:22 UTC by darliiin

**Summary**
**Test task**
t7 - get only the filenames
Script should get a folder as an argument and return a list of all unique files with extensions but without the absolute path (including in the nested directories). only -f option is allowed for the use of find command, i.e.: find /tmp -type f. Which should find all files in all nested dirs and then process the output by using expansion.

name the file: `chapter2-l2-t7-get-unique-files.sh`

example of the call:

`chapter2-l2-t7-get-unique-files.sh /tmp/bazel`
```

main.sh.x.c
main.c
dummy.c
zutil.c
uncompr.c
trees.c
minigzip.c
infcover.c
example.c
inftrees.c
```
**my result**
`./chapter2-l2-t7-get-unique-files.sh ~/Загрузки/a `
**output**
```
photo_2023-03-20_16-00-58.jpg
Maven_spring_demo.zip
ideaIU-2022.3.3.tar.gz
google-chrome-stable_current_amd64.deb
dariyanalimova.p12
```

2023-04-14 04:55 UTC, kseniyashaydurova requested changes

2023-04-14 04:55 UTC, kseniyashaydurova commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +var=$1
Bad variable name

2023-04-14 04:55 UTC, kseniyashaydurova commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +file_name=()
Let's try to use `sort` and `uniq` bash commands to avoid having separate list

2023-04-14 12:41 UTC, darliiin commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +file_name=()
done

2023-04-14 12:41 UTC, darliiin commented on chapter2/tests/t7/chapter2-l2-t7-get-unique-files.sh
> +var=$1
done

2023-04-19 09:46 UTC, kseniyashaydurova approved these changes

2023-04-26 15:01 UTC, merged