feat: t8 - chapter2-l4-t8-get-tcp-listening-connections.sh file
darliiin/devops-camp-2023 pull request #7
Opened 2023-04-03 11:06 UTC by darliiin

**Summary
Test Task**
**t8 - display new tcp listening connections in the range 10000-10100**
When you launch the script it should initially list all tcp connections in the port range 10000-10100 New found connections should be displayed in the console as soon as they're identified

**name the file:**
` chapter2-l4-t8-get-tcp-listening-connections.sh`

**example of the call:**
I initially ran 2 nginx instances bound to 2 different ports (10000, 10001)
`chapter2-l4-t8-get-tcp-listening-connections.sh`

**output:**
```
Local Address:Port   Peer Address:Port
127.0.0.1:10000       0.0.0.0:* 
127.0.0.1:10001       0.0.0.0:* 
```
then 10s later I launch another nginx on port 10002, I should immediately get a single line APPENDED
`127.0.0.1:10002       0.0.0.0:* `

so in that particular example over time I will get 3 rows
```
Local Address:Port   Peer Address:Port
127.0.0.1:10000       0.0.0.0:* 
127.0.0.1:10001       0.0.0.0:* 
127.0.0.1:10002       0.0.0.0:* 
```
If I have NO listening connections in such port range, then I should display "No TCP listening sockets found bound to ports in 10000-10100 range" every N seconds.

**my results:**
./chapter2-l4-t8-get-tcp-listening-connections.sh

**output:**
```
0.0.0.0:10000 0.0.0.0:*  
0.0.0.0:10001 0.0.0.0:*    
[::]:10000 [::]:*  
[::]:10001 [::]:*  
    
No listening TCP sockets bound to ports in the range 10000-10100
No listening TCP sockets bound to ports in the range 10000-10100
No listening TCP sockets bound to ports in the range 10000-10100

0.0.0.0:10005 0.0.0.0:*  
0.0.0.0:10000 0.0.0.0:*  
0.0.0.0:10001 0.0.0.0:*  
[::]:10005 [::]:*  
[::]:10000 [::]:*  
[::]:10001 [::]:*  

No listening TCP sockets bound to ports in the range 10000-10100
No listening TCP sockets bound to ports in the range 10000-10100
```

2023-04-21 10:54 UTC, kseniyashaydurova requested changes

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +ports=()
Let's add separate vars for ports ranges (i.e. one for start and another for end)

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +sleep 5;
Let's add a separate variable for timeout

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
Why you file is located on this path? `./chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh` Why not `./chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh`

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#TCP connections in the port range 10000-10100
Please always write comments like this `# `

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
Script doesn't work correctly 
![image](https://user-images.githubusercontent.com/26448672/233618197-32c46858-7491-48a1-87d9-2f8f10397ed6.png)

Here I listen 10000 port with nginx, but your script shows nothing

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  num_port=$(ss -tan '( sport >= :10000 and sport <= :10100 )' | awk '{print $4, $5, $6, $7}' | cut -d: -f4 | cut -d' ' -f1)
So you display here all sockets? `ss -a`, so not listening sockets would be also displayed in output?

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    connections=$(ss -tan '( sport >= :10000 and sport <= :10100 )' | awk '{print $4, $5, $6, $7}')
Why do you repeat the same command again? Let's override codes to avoid it (DRY)

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    "
What is the problem here with quotes?

2023-04-21 10:54 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
So I was unable to see with your script any opened connections

2023-04-24 20:31 UTC, dmitry-mightydevops commented
@darliiin pls always move into DRAFT

i.e. feedback received
- add WIP
- remove NEEDS REVIEW
- move OPEN > DRAFT

2023-04-24 20:34 UTC, dmitry-mightydevops requested changes

2023-04-24 20:34 UTC, dmitry-mightydevops commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    connections=$(ss -tan '( sport >= :10000 and sport <= :10100 )' | awk '{print $4, $5, $6, $7}')
@darliiin don't hardcode vars that can change over time. Extract `10000 and sport <= :10100` into vars on top of the file

2023-04-24 20:34 UTC, dmitry-mightydevops commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    connections=$(ss -tan '( sport >= :10000 and sport <= :10100 )' | awk '{print $4, $5, $6, $7}')
you need to listen for tcp listening sockets i.e.

`ss -ltnp -at '$PORT_RANGE'`

2023-04-24 20:34 UTC, dmitry-mightydevops commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +sleep 5;
As usual - don't hardcode the values

2023-04-28 16:08 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    "
corrected

2023-04-28 16:09 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
done

2023-04-28 16:09 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#TCP connections in the port range 10000-10100
corrected

2023-04-28 16:09 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
corrected

2023-04-28 16:09 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +ports=()
done

2023-04-28 16:10 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +ports=()
done

2023-04-28 16:10 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +ports=()
done

2023-04-28 16:10 UTC, darliiin commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +sleep 5;
done

2023-04-28 20:08 UTC, dmitry-mightydevops approved these changes

2023-04-28 20:08 UTC, dmitry-mightydevops commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +sleep "${time_sleep}";
wrong padding from the left - always convert spaces to tabs

2023-05-03 02:50 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    # if the connection is new, print to stdout and add the port to the arraylast_port
```suggestion
    # if the connection is new, print to stdout and add the port to the `ports` array
```

2023-05-03 02:50 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  echo "No listening TCP sockets bound to ports in the range 10000-10100"
Please add left indent here

2023-05-03 02:50 UTC, kseniyashaydurova commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  echo "No listening TCP sockets bound to ports in the range 10000-10100"
Also you have hard coded ports ranges in your echo message. You should use your `first_port` and `last_port` vars

2023-05-03 02:50 UTC, kseniyashaydurova commented on chapter2/tests/t4/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +#!/bin/bash
Still doesn't work correctly for me:

1. I still have `No listening TCP sockets` message (I suppose that happens because I start nginx processes with `sudo`)
![image](https://user-images.githubusercontent.com/26448672/235824005-0ea0c212-d7e4-4528-9e83-7fc6f130de20.png)

2. When I start you script with `sudo` command too, it started working ok and showed 2 current TCP connections, but then it started to print always `No listening TCP sockets bound to ports in the range 10000-10100`, but I didn't close my connections, so script shouldn't behave like that
![image](https://user-images.githubusercontent.com/26448672/235824137-0c9052a5-7d7e-46fa-a0bb-1c383d3198a6.png)

2023-05-03 19:17 UTC, darliiin commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  echo "No listening TCP sockets bound to ports in the range 10000-10100"
done

2023-05-03 19:17 UTC, darliiin commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +  echo "No listening TCP sockets bound to ports in the range 10000-10100"
done

2023-05-03 19:17 UTC, darliiin commented on chapter2/tests/t8/chapter2-l4-t8-get-tcp-listening-connections.sh
> +    # if the connection is new, print to stdout and add the port to the arraylast_port
done

2023-06-12 09:02 UTC, kseniyashaydurova approved these changes

2023-06-12 09:07 UTC, merged