feat: t3 - chapter2-t3-velero-eks-diff.sh file
darliiin/devops-camp-2023 pull request #8
Opened 2023-04-05 15:13 UTC by darliiin

**Summary
Test Task
T3 - Find namespaces without the backup**
We need to come up with a prototype solution that will give us the list of kubernetes namespaces we haven't backed up. We have a special backup manifest that contains the configurationf for the backups.

**For example:** https://gist.github.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74

the configuration is in the schedules.[].includedNamespaces block of the file

   ```
     schedules:
          system:
            labels:
              backup: system
            schedule: "@every 24h"
            template:
              ttl: "480h"
              includedNamespaces:
                - cert-manager
                - ingress-nginx
                - kube-node-lease
                - kube-public
                - kube-system
                - ops
                - opsgenie
                - default
              excludedResources:
                - orders.acme.cert-manager.io
                - challenges.acme.cert-manager.io
                - certificaterequests.cert-manager.io
          a3fs:
            labels:
              backup: a3fs
            schedule: "@every 24h"
            template:
              ttl: "480h"
              includedNamespaces:
                - a3fs
```
we're supposed to run the following command:

`➜ kubectl get ns -o="custom-columns=NAME:.metadata.name" --no-headers`

that will give us a list of all namespaces in the kubernetes cluster.

The result of this command is https://gist.github.com/dmitry-mightydevops/297c4e235b61982f21a0bbbf7319ac24

Implement the bash script that will find all namespaces in the cluster that has not been configured in the velero manifest. I.e. operation on sets.

**name the file:** chapter2-t3-velero-eks-diff.sh
**example of the call:**
```
./chapter2-t3-velero-eks-diff.sh
```
**example output:**
```
- aacct
- aaoa-ari-cleara
- arthrexvip
- axia
- camp-dotnet
- camp-python
- camp-unity
- caregiver
- ci-experiments
- ci-experiments-apps
...all namespaces should be listed that are not configured for the backup
```

**nuances:**

- your bash script should download these 2 gists using curl and pass them into stdout of other commands you're using.
- you can use any CLI tool from the distro you're using to calculate the diff between two data blocks and come up with the output above.
- you can use yq or jq cli if necessary for your ops.

**my results:**
`./chapter2-t3-velero-eks-diff.sh`
**output:**
`aacct
aaoa-ari-cleara
arthrexvip
axia
camp-dotnet
camp-python
camp-unity
caregiver
ci-experiments
ci-experiments-apps
commlrning
debug
demo
dev
disvr
dogvr
enrgy
fallon-medica
faroeve
fbmm
firearm
github-inactivity
igntpb
inkus
insights-agent
interesnee
jenkins
kubewatch
macroplate
mailhog
maunf
medvr
metrics-server
nrs
oprs
prfctpt
redis
rma
saritasa-android
saritasa-ios
saritasa-jira-qa-tool
saritasa-php
saritasa-python
saritasa-qa
saritasa-unity
scripta
sgvr
sportsthread
streetparking
tekton-pipelines-experiments
toro
tran
trapi
trivver
utd
utils
velero
vrcatchup
`

2023-04-14 04:37 UTC, kseniyashaydurova requested changes

2023-04-14 04:37 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +if [[ "$VELERO_BACKUP_NAMESPACES" == "404: Not Found"  ]]; then
Not nice implementation, you have here 2 absolutely similar `if` conditions but for different file names, let's wrap this to 1 separate function, which will check whether any file was loaded or not, so it will accept `uri` param and raise error that file wan't found on this uri

2023-04-14 04:37 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +for namespace in "${KUBERNETES_NAMESPACES[@]}"; do
Let's try to improve this solutions with https://linuxhint.com/bash_uniq_command/
So then you won't need to push both files contents to lists and you will avoid double brackets in your `KUBERNETES_NAMESPACES` and `VELERO_MANIFEST` vars

2023-04-14 04:37 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +VELERO_MANIFEST=($(echo "$VELERO_BACKUP_NAMESPACES" | yq ".spec.source.helm.values" \
This var contains not velero manifest, but namespaces from velero manifest, so suggest to call it like this 
```suggestion
VELERO_NAMESPACES=($(echo "$VELERO_BACKUP_NAMESPACES" | yq ".spec.source.helm.values" \
```

2023-04-14 04:37 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +# download kubernetes namespaces
Also if you do similar stuff, add comments in a similar way, I think here would be much better to add similar to `VELERO_MANIFEST` comment:
```suggestion
# list of actual kubernetes namespaces
```

2023-04-14 11:08 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +# download kubernetes namespaces
done

2023-04-14 11:08 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +VELERO_MANIFEST=($(echo "$VELERO_BACKUP_NAMESPACES" | yq ".spec.source.helm.values" \
done

2023-04-14 11:08 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +for namespace in "${KUBERNETES_NAMESPACES[@]}"; do
done

2023-04-14 11:08 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +if [[ "$VELERO_BACKUP_NAMESPACES" == "404: Not Found"  ]]; then
done

2023-04-19 09:40 UTC, kseniyashaydurova requested changes

2023-04-19 09:40 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +# list of kubernetes namespaces that are not backed up
It seems that this comment is not actual anymore, let's remove it

2023-04-19 09:40 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +VELERO_BACKUP_NAMESPACES=$(curl -sSL https://gist.github.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74/raw/velero.yaml)
```suggestion
VELERO_BACKUP=$(curl -sSL https://gist.github.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74/raw/velero.yaml)
```

2023-04-19 09:40 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +echo "$VELERO_NAMESPACES" > combined.txt
Please reorganize your solution without `txt` file usage, just echo both and sort and make unique

2023-04-19 09:40 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file "kubernetes-namespaces.txt" "KUBERNETES_NAMESPACES"
Please check case when `velero.yaml` file correctly loaded and `kubernetes-namespaces.txt` doesn't exist. In such a scenario your script just returns backed up namespaces, but should print error message that `kubernetes-namespaces.txt` file doesn't exist

2023-04-19 12:54 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file "kubernetes-namespaces.txt" "KUBERNETES_NAMESPACES"
done

2023-04-19 12:54 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +echo "$VELERO_NAMESPACES" > combined.txt
done

2023-04-19 12:54 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +VELERO_BACKUP_NAMESPACES=$(curl -sSL https://gist.github.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74/raw/velero.yaml)
done

2023-04-19 12:54 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +# list of kubernetes namespaces that are not backed up
done

2023-05-03 02:18 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file "kubernetes-namespaces.txt" "KUBERNETES_NAMESPACES"
This doesn't work correctly

2023-05-03 02:25 UTC, kseniyashaydurova requested changes
@darliiin Can you test your solutions before re requesting PRs? Please always be sure that all your scripts work 100% before opening PR.

2023-05-03 02:25 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +# function to check if a file was loaded or not
Please add docs according to our guideline

2023-05-03 02:25 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file "velero.yaml" "${VELERO_BACKUP}"
That looks rather strange
![image](https://user-images.githubusercontent.com/26448672/235821691-3cb11a83-a543-40a3-8317-3af97e40a4f2.png)

Inside function you have `$1 -> uri`, `$2 -> file` but here you pass these params in different order and error message becomes not clear at all

2023-05-03 02:25 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +if [[ ! -f "kubernetes-namespaces.txt" ]]; then
This looks rather strange and now you script doesn't work and always raises `ERROR: kubernetes-namespaces.txt file not found`, but it exists
![image](https://user-images.githubusercontent.com/26448672/235821888-a0c2ba68-f784-40bb-b9c5-9cee4c7a13c5.png)

Why do you check here for a local file `kubernetes-namespaces.txt` - I don't understand

2023-05-03 02:25 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +(sort <<< "$VELERO_NAMESPACES"$'\n'"$KUBERNETES_NAMESPACES" | uniq -u)
Why do you need brackets here?

2023-05-04 16:22 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +# function to check if a file was loaded or not
done

2023-05-04 16:23 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file "kubernetes-namespaces.txt" "KUBERNETES_NAMESPACES"
I'm sorry, I seem to have overlooked something

2023-05-04 16:23 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +check_file "velero.yaml" "${VELERO_BACKUP}"
done

2023-05-04 16:24 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +if [[ ! -f "kubernetes-namespaces.txt" ]]; then
ok, I removed this part of the code, it was not needed

2023-05-04 16:24 UTC, darliiin commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +(sort <<< "$VELERO_NAMESPACES"$'\n'"$KUBERNETES_NAMESPACES" | uniq -u)
removed

2023-06-05 05:37 UTC, kseniyashaydurova approved these changes

2023-06-05 05:44 UTC, merged